import { Inter } from "next/font/google";
import "./globals.css";
import SideDrawer from "@/components/large/Sidedrawer/SideDrawer";
import TopBar from "@/components/large/TopBar/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mainStructure">
        <div className="sidedrawer">
        <SideDrawer/> 
          </div> 
          
       <div className="content">
       <div className="topbar">
         <TopBar/> 
          </div> 
            {children}
       </div>
      
        </main>
       
       
        </body>
    </html>
  );
}
